/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lhl_bsdiff_BsDiffUtil */

#ifndef _Included_com_lhl_bsdiff_BsDiffUtil
#define _Included_com_lhl_bsdiff_BsDiffUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lhl_bsdiff_BsDiffUtil
 * Method:    genDiff
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_lhl_bsdiff_BsDiffUtil_genDiff
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
