/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lhl_bspatch_BsPatchUtil */

#ifndef _Included_com_lhl_bspatch_BsPatchUtil
#define _Included_com_lhl_bspatch_BsPatchUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lhl_bspatch_BsPatchUtil
 * Method:    patch
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_lhl_bspatch_BsPatchUtil_patch
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
